model:
    dim_ssm_io: 256
    dim_ssm_state: 32
    num_ssm_layers: 1
    output_dim: 2
    rng_seed: 42
    dt_min: 0.001
    dt_max: 0.01
    dropout_p: 0.03
    ssm_dropout_p: 0.03

optimizer:
  lr: 0.005
  weight_decay: 0.01
  mode: all