model:
    dim_ssm_io: 512
    dim_ssm_state: 128  
    num_ssm_layers: 4
    num_dataset_groups: 10
    input_dim: 625
    output_dim: 2
    rng_seed: 42
    dt_min: 0.001
    dt_max: 0.01
    dropout_p: 0.01
    context_dim: 0

optimizer:
  lr: 0.001
  weight_decay: 0.01
  mode: all