# Wandb sweep configuration
program: scripts/training/nlb_downstream.py
method: grid
metric:
  name: final/r2
  goal: maximize
run_cap: 200  
early_terminate:
  type: hyperband
  min_iter: 10
parameters:
  dataset.name:
    values: [mc_rtt_prepend, mc_area2bump_prepend]
  optimizer.algorithm_kwargs.learning_rate:
    values: [0.04, 0.05, 0.6, 0.7, 0.8]
  model.ssm_layer_cls: 
    values: ["ContinuousSSMLayer"]
  model.ssm_layer_kwargs.a_initialisation:
    values: ["s4d_real"]
  # model.ssm_layer_kwargs.rand_real:
  #   values: [true, false]
  # model.ssm_layer_kwargs.rand_imag:
  #   values: [true, false]

wandb:
  project: foundational_ssm_downstream_sgd_sweeps
  tags: [neural, behavior, downstream, decoding, sweep]
  entity: melinajingting-ucl
  run_prefix: rtt
