wandb:
  project: foundational_ssm_downstream_sweep
  tags: [neural, behavior, downstream, decoding, rtt]
  entity: melinajingting-ucl

dataset:
  name: mc_rtt_prepend
  batch_size: 64
  phase: 'test'
  skip_timesteps: 60

model:
  checkpoint: melinajingting-ucl/foundational_ssm_pretrain/l2_reaching_normalized_checkpoint:best

optimizer:
  mode: all

training:
  epochs: 701
  log_val_every: 100
  save_checkpoints: true
  checkpoint_every: 100
  save_activations: false
  log_pred_and_activations_every: 999
  from_scratch: true


rng_seed: 42
device: cuda