# Wandb sweep configuration
program: scripts/training/nlb_downstream.py
method: bayes
metric:
  name: final/r2
  goal: maximize
run_cap: 2000  # Limit total number of runs
early_terminate:
  type: hyperband
  min_iter: 10
parameters:
  optimizer.mode:
    values: [all]
  model.ssm_dim:
    values: [128]
  model.ssm_io_dim:
    values: [256]
  model.ssm_num_layers:
    values: [2]
  optimizer.hyperparams.learning_rate:
    min: 0.005
    max: 0.05
  model.dropout_p:
    values: [0.03]

# Fixed parameters (not swept)
wandb:
  project: foundational_ssm_rtt_sgd_sweep
  tags: [neural, behavior, downstream, decoding, sweep]
  entity: melinajingting-ucl
  run_prefix: rtt
